import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { MARK_INTRINSIC, MARK_SRC, WORD_INTRINSIC, WORD_LIGHT_SRC, WORD_SRC } from './assets';

/*
  What this guards.

  The brand assets are generated by scripts/build-brand.py, which needs Python and Pillow and
  therefore does NOT run in CI or on anyone's machine by default. That is the right trade —
  the outputs are checked in, so building and deploying need neither — but it leaves a gap: an
  edit to the script, or a regenerated master, can change an asset's dimensions while the
  numbers BasisLogo hands the browser stay behind. Nothing would error. The bar would just
  reserve the wrong box on first paint and reflow when the logo arrives, which is invisible on
  a warm local load and obvious on a cold mobile one.

  So this reads the real PNGs off disk and checks them against what the component claims.

  Read with node:fs rather than an import: vitest leaves assets unprocessed, so `import mark
  from './x.png'` resolves to a stub path and every assertion below would pass against
  nothing. Node builtins are available here because tests compile under tsconfig.test.json.
*/

const ROOT = process.cwd();
const PUBLIC = join(ROOT, 'public');

/**
 * A PNG's dimensions, straight out of the IHDR chunk.
 *
 * Eight bytes of signature, then the chunk length and type, then width and height as
 * big-endian uint32s at offsets 16 and 20. Twelve lines instead of an image dependency the
 * app does not otherwise need.
 */
function pngSize(path: string): { width: number; height: number } {
  const buf = readFileSync(path);
  expect(buf.subarray(1, 4).toString('ascii'), `${path} is not a PNG`).toBe('PNG');
  expect(buf.subarray(12, 16).toString('ascii'), `${path} has no IHDR`).toBe('IHDR');
  return { width: buf.readUInt32BE(16), height: buf.readUInt32BE(20) };
}

/** Every asset path the component or the document references, and what it must be. */
const ASSETS = [
  { src: MARK_SRC, intrinsic: MARK_INTRINSIC },
  { src: WORD_SRC, intrinsic: WORD_INTRINSIC },
  { src: WORD_LIGHT_SRC, intrinsic: WORD_INTRINSIC },
];

describe('brand assets', () => {
  it.each(ASSETS)('$src exists at the size BasisLogo declares', ({ src, intrinsic }) => {
    const path = join(PUBLIC, src);
    expect(existsSync(path), `${src} is missing — run scripts/build-brand.py`).toBe(true);
    expect(pngSize(path)).toEqual(intrinsic);
  });

  /*
    The two wordmarks are the same image in two colours, and <picture> swaps between them on
    prefers-color-scheme. If they ever differ in size the swap becomes a layout change: the bar
    would be one width in light mode and another in dark, which is the kind of thing nobody
    sees until they toggle the OS theme with the page open.
  */
  it('ships both wordmarks at identical dimensions', () => {
    const dark = pngSize(join(PUBLIC, WORD_SRC));
    const light = pngSize(join(PUBLIC, WORD_LIGHT_SRC));
    expect(light).toEqual(dark);
  });

  /*
    The master is the only source. Losing it does not break the build — the derived assets are
    checked in — which is exactly why its absence needs to fail somewhere: without it nobody
    can regenerate anything, and the loss would go unnoticed until someone tried.
  */
  it('keeps the master render in the repo', () => {
    expect(existsSync(join(ROOT, 'brand', 'basis-logo-master.png'))).toBe(true);
  });
});

describe('document icons', () => {
  const html = readFileSync(join(ROOT, 'index.html'), 'utf8');

  it.each(['/favicon-32.png', '/favicon-180.png'])('%s is linked and present', (href) => {
    expect(html).toContain(`href="${href}"`);
    expect(existsSync(join(PUBLIC, href))).toBe(true);
  });

  /*
    The favicon that shipped before this was a purple lightning bolt left over from a
    template — #863bff, a colour that appears nowhere in Basis. It is gone, and so is the SVG
    that carried it. This fails if either comes back, or if a link is left pointing at a file
    that no longer exists, which would silently fall back to /favicon.ico and a blank tab.
  */
  it('no longer references the removed favicon.svg', () => {
    expect(html).not.toContain('favicon.svg');
    expect(existsSync(join(PUBLIC, 'favicon.svg'))).toBe(false);
  });
});
