/**
 * Output for coding agents.
 *
 * Three formats, all serialised from the generated system with nothing invented:
 *   - a compact context block to paste into a chat
 *   - BASIS.md, a file to drop in a repo as the design source of truth
 *   - a build prompt for a specific kind of screen
 *
 * These are text generators. Basis does not integrate with Claude Code, Cursor, v0 or
 * anything else, and the copy in the UI must not imply that it does.
 */

import { auditAccessibility } from './accessibility';
import { buildComponentStates } from './componentStates';
import { buildProductPatterns } from './productPatterns';
import { buildSemanticTokens } from './semanticTokens';
import { buildSystemDna } from './systemDna';
import type { DesignSystemOutput } from './types';

/** The rules every generated context repeats, because agents drift without them. */
const AGENT_RULES = [
  'Use only the tokens below. Do not introduce colors that are not listed.',
  'Do not invent spacing values. Use the spacing scale.',
  'Do not invent radii. Use the radius scale.',
  'Use the semantic token names, not raw hex values, wherever the target stack supports variables.',
  'Implement every interaction state listed for a component: default, hover, focus, active, disabled.',
  'Keep the visible focus indicator. Never remove outlines without replacing them.',
  'Respect prefers-reduced-motion: disable transitions when it is set.',
  'Do not add gradients, glows or shadows that are not in the system.',
];

function tokenLines(output: DesignSystemOutput): string[] {
  return buildSemanticTokens(output).map((t) => `  ${t.name}: ${t.value}`);
}

/** Compact block for pasting into a chat window. */
export function buildAiContext(output: DesignSystemOutput): string {
  const dna = buildSystemDna(output);
  const patterns = buildProductPatterns(output);

  // `null` marks a line that may not apply; '' is a deliberate blank line and is kept.
  const lines: Array<string | null> = [
    'BASIS DESIGN SYSTEM',
    '',
    `Product: ${output.category}`,
    `Brief: ${output.query}`,
    `Design direction: ${output.style.name}`,
    dna.traits.length > 0 ? `Character: ${dna.traits.map((t) => t.trait).join(', ')}` : null,
    '',
    'TOKENS',
    ...tokenLines(output),
    '',
    'TYPOGRAPHY',
    `  Heading: ${output.typography.heading}`,
    `  Body: ${output.typography.body}`,
    output.typography.css_import ? `  Import: ${output.typography.css_import}` : null,
    '',
    'LAYOUT',
    `  Pattern: ${output.pattern.name}`,
    `  Sections: ${output.pattern.sections}`,
    '',
    output.anti_patterns ? `AVOID\n  ${output.anti_patterns}` : null,
    output.anti_patterns ? '' : null,
    `SCREENS WORTH BUILDING (Basis recommendations for ${patterns.family}, not engine output)`,
    ...patterns.patterns.map((p) => `  - ${p}`),
    '',
    'RULES',
    ...AGENT_RULES.map((r) => `  - ${r}`),
  ];

  return lines.filter((line): line is string => line !== null).join('\n');
}

/** The file to commit into a repo. */
export function buildBasisMarkdown(output: DesignSystemOutput): string {
  const dna = buildSystemDna(output);
  const tokens = buildSemanticTokens(output);
  const states = buildComponentStates(output);
  const audit = auditAccessibility(output);
  const patterns = buildProductPatterns(output);

  const byGroup = (group: string) => tokens.filter((t) => t.group === group);

  const lines: string[] = [];
  const push = (...l: string[]) => lines.push(...l);

  push('# BASIS.md', '');
  push(
    'The design source of truth for this project, generated by Basis.',
    'Treat it as authoritative: if the code and this file disagree, the code is wrong.',
    '',
  );

  push('## Product context', '');
  push(`- **Product type:** ${output.category}`);
  push(`- **Brief:** ${output.query}`);
  push(`- **Design direction:** ${output.style.name}`);
  if (output.style.best_for) push(`- **The direction suits:** ${output.style.best_for}`);
  push('');

  push('## Design principles', '');
  push(dna.summary, '');
  if (dna.traits.length > 0) {
    for (const t of dna.traits) push(`- **${t.trait}** — from \`${t.field}\`: "${t.evidence}"`);
    push('');
  }

  push('## Color', '');
  push('| Token | Value | Role | Origin |', '| --- | --- | --- | --- |');
  for (const t of byGroup('color')) {
    push(`| \`${t.name}\` | \`${t.value}\` | ${t.role} | ${t.origin} |`);
  }
  push('');
  push(
    '`generated` came from the dataset for this product. `derived` was computed from a generated value.',
    '`default` is a Basis constant because the dataset has no value for that role.',
    '',
  );

  push('## Typography', '');
  push(`- **Heading:** ${output.typography.heading}`);
  push(`- **Body:** ${output.typography.body}`);
  if (output.typography.css_import) push('', '```css', output.typography.css_import, '```');
  push('');

  push('## Spacing', '');
  push('| Token | Value |', '| --- | --- |');
  for (const t of byGroup('space')) push(`| \`${t.name}\` | \`${t.value}\` |`);
  push('');

  push('## Radius', '');
  push('| Token | Value |', '| --- | --- |');
  for (const t of byGroup('radius')) push(`| \`${t.name}\` | \`${t.value}\` |`);
  push('');

  push('## Motion', '');
  push(`- **Duration:** ${output.motion.duration} (${output.motion.source === 'style' ? 'from the matched style' : 'Basis default'})`);
  push('- All motion must be disabled under `prefers-reduced-motion: reduce`.', '');

  push('## Components', '');
  for (const c of states) {
    push(`### ${c.component}`, '');
    push('| State | Background | Text | Border |', '| --- | --- | --- | --- |');
    for (const s of c.applicable) {
      const st = c.states[s];
      push(`| ${s} | \`${st.background}\` | \`${st.foreground}\` | \`${st.border}\` |`);
    }
    push('');
  }

  push('## States', '');
  push(
    'Every interactive component must implement default, hover, focus, active and disabled.',
    'Loading, success and error apply wherever the component can be async or validated.',
    'State colours above are derived from the resting appearance, not separately generated.',
    '',
  );

  push('## Accessibility', '');
  for (const f of audit.findings) {
    const mark = f.status === 'pass' ? 'PASS' : f.status === 'warning' ? 'WARNING' : 'NEEDS ATTENTION';
    push(`- **${f.title}** — ${mark}. ${f.detail}`);
    if (f.fix) push(`  - Fix: ${f.fix}`);
  }
  push('');

  push('## Screens worth building', '');
  push(`Basis recommendations for ${patterns.family}. These are guidance, not engine output.`, '');
  for (const p of patterns.patterns) push(`- ${p}`);
  push('');
  if (patterns.keyConsiderations) {
    push(`From the product dataset for ${output.category}: ${patterns.keyConsiderations}`, '');
  }

  push('## Do', '');
  for (const r of AGENT_RULES) push(`- ${r}`);
  push('');

  push("## Don't", '');
  if (output.anti_patterns) {
    for (const a of output.anti_patterns.split('+').map((s) => s.trim()).filter(Boolean)) {
      push(`- ${a} — recorded against ${output.category} as something that breaks this kind of product.`);
    }
  }
  push('- Add colors, spacing values or radii that are not in the tables above.');
  push('- Remove focus indicators.');
  push('- Convey state with colour alone; pair it with an icon or text.');
  push('');

  push('## Token rules', '');
  push(
    '1. Reference tokens by semantic name, never by raw value.',
    '2. If a needed role has no token, add it here first, then use it.',
    '3. Do not hardcode a value that already exists as a token.',
    '4. Derived and default tokens are still tokens: change them here, not at the call site.',
    '',
  );

  return lines.join('\n');
}

export type BuildTarget =
  | 'landing'
  | 'dashboard'
  | 'mobile'
  | 'saas'
  | 'ecommerce'
  | 'portfolio'
  | 'custom';

export const BUILD_TARGETS: Array<{ id: BuildTarget; label: string; brief: string }> = [
  { id: 'landing', label: 'Landing page', brief: 'a marketing landing page' },
  { id: 'dashboard', label: 'Dashboard', brief: 'an analytics dashboard' },
  { id: 'mobile', label: 'Mobile app', brief: 'a mobile application' },
  { id: 'saas', label: 'SaaS application', brief: 'a SaaS application shell' },
  { id: 'ecommerce', label: 'E-commerce interface', brief: 'an e-commerce storefront' },
  { id: 'portfolio', label: 'Portfolio', brief: 'a portfolio site' },
  { id: 'custom', label: 'Custom', brief: '' },
];

/** A full implementation prompt for one kind of build. */
export function buildImplementationPrompt(
  output: DesignSystemOutput,
  target: BuildTarget,
  customBrief = '',
): string {
  const spec = BUILD_TARGETS.find((t) => t.id === target) ?? BUILD_TARGETS[0];
  const brief = target === 'custom' ? customBrief.trim() || 'the interface described below' : spec.brief;

  const lines: Array<string | null> = [
    `Build ${brief} for ${output.category}.`,
    '',
    'Use the Basis design system below as the source of truth. It is not a suggestion:',
    'every color, size and radius you use must come from it.',
    '',
    buildAiContext(output),
    '',
    'IMPLEMENTATION REQUIREMENTS',
    '',
    `- Build ${brief}, using the screens listed above as the scope.`,
    '- Define the tokens as CSS custom properties (or the equivalent in the target stack) once, at the root.',
    '- Reference tokens by name throughout. No raw hex values in component code.',
    '- Implement default, hover, focus, active and disabled for every interactive element.',
    '- Keyboard: everything reachable by Tab, in visual order, with a visible focus ring.',
    '- Verify text contrast meets WCAG AA before you finish.',
    '- Make it responsive from 360px up. Mobile is not a squeezed desktop.',
    `- The design direction is "${output.style.name}".${output.style.keywords ? ` It reads as: ${output.style.keywords}.` : ''}`,
    output.anti_patterns ? `- Avoid: ${output.anti_patterns}.` : null,
    '',
    'Ask before deviating from the system. If something is missing from it, say so rather',
    'than inventing a value.',
  ];

  return lines.filter((l): l is string => l !== null).join('\n');
}
